services:
  build-manager:
    build:
      context: ./
      dockerfile: ./build-manager/docker/Dockerfile
      args:
        - DOCKER_GID=964
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./repository:/repository:cached
      - ./packagelist.json:/repository-builder/packagelist.json:ro
      - package-staging:/package-staging
      - aur-package-list:/aur-package-list
    restart: on-failure
    networks:
      - default

  nginx:
    image: nginx:latest
    volumes:
      - ./repository:/usr/share/nginx/html:ro
      - ./assets/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: on-failure
    networks:
      - default
      - traefik-reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-reverse-proxy"
      - "traefik.http.routers.docker-aur-cache-nginx.rule=Host(`${BASE_URL:-docker-aur-cache.localhost}`)"
      - "traefik.http.routers.docker-aur-cache-nginx.entrypoints=http"
      - "traefik.http.routers.docker-aur-cache-nginx.tls=false"

volumes:
  package-staging:
  aur-package-list:

# You can find the Traefik reverse proxy container on GitHub
# https://github.com/CrazyVito11/traefik-reverse-proxy
networks:
  traefik-reverse-proxy:
    name: traefik-reverse-proxy
    external: true
